### ISSUE TITLE
Gem version 2.8.3 cannot load

### ISSUE THREAD

**Issue by jholton** [govdelivery/govdelivery-tms-ruby#23]
@alexives Thanks for the release.  Unfortunately, it appears that the changes to code regarding versioning causes errors for us.

`VERSION = File.read(File.join(__dir__, "../../../.version")).freeze`

The `.version` file doesn't exist on our servers, and therefore an error is thrown when the gem is loaded.

```
Errno::ENOENT: No such file or directory @ rb_sysopen - /my/gem/path/.gem/ruby/2.3.0/gems/govdelivery-tms-2.8.3/lib/govdelivery/tms/../../../.version
	from /my/gem/path/.gem/ruby/2.3.0/gems/govdelivery-tms-2.8.3/lib/govdelivery/tms/version.rb:3:in `read'
```

cc:  @rtluu

**Comment by alexives** [comment]
Just pushed 2.8.4

**Comment by jholton** [comment]
Looks good.  Thanks!
